### PR TITLE
moved GUI code under colin so I would try to use class variable, added show inventory 

### PR DESCRIPTION
**Pull request by cdgg1231**

### CODE REVIEW

**Review by uoods — APPROVED** [review]
I see that the variables are changed

**Review by uoods — APPROVED** [review]
moved folder +

**Review by Huyentram27 — APPROVED** [review]
variable name changed looks correct

**Review by uoods — COMMENTED** [review]
noted

**Review by uoods — APPROVED** [review]

**Review by uoods — APPROVED** [review]
new variable name seen

**Pull request merged**
